### ISSUE TITLE
Design discussion

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-calendar#9]
Design questions:

- Do we prefer a dropdown for month/year or something else? I like the simplicity of Duet's but the native `<selects>` don't match custom selects. Maybe we should take inspiration from `<input type="date">` as a baseline to start from. Chromium has a neat implementation for this. Personally, I think Firefox's month/year view is the best. (See screenshots below.)

- Localization is a must for days/months/etc. Are we scoping this to Gregorian-only? (I don't have any experience with alternate calendars.)

- Since we're talking about design, are we looking to translate Duet DP from Stencil => Lit or are we looking to build something from the ground up, potentially using code from Duet?

I'm sure we'll have more questions as this progresses.

---

### Browser Date Pickers

Some screenshots, for inspiration.

Chromium

<img width="250" alt="CleanShot 2022-01-13 at 13 46 02@2x" src="https://user-images.githubusercontent.com/55639/149390568-46da9b05-ff8d-4187-9d9c-ada2058744f3.png">

<img width="247" alt="CleanShot 2022-01-13 at 13 46 20@2x" src="https://user-images.githubusercontent.com/55639/149390596-fe7738b2-c095-4ab1-8f3b-3f3a6dec242e.png">

Firefox

<img width="299" alt="CleanShot 2022-01-13 at 13 47 20@2x" src="https://user-images.githubusercontent.com/55639/149390774-e62ec58e-212f-4cc9-b4a1-c5a888f343e8.png">

<img width="298" alt="CleanShot 2022-01-13 at 13 47 41@2x" src="https://user-images.githubusercontent.com/55639/149390798-44c8fecd-216c-42a2-9366-ea9c2beccde9.png">

Safari:

<img width="172" alt="CleanShot 2022-01-13 at 13 48 30@2x" src="https://user-images.githubusercontent.com/55639/149390898-14d7ad80-70ba-4275-96b1-3e76b4ad0f58.png">

(no month/year view)

---

Aside: I love Duet and I still think it's the gold standard for custom element date pickers, but I recently came across this. It may be worth a discussion as well.

Repo: https://github.com/motss/app-datepicker
Demo: https://motss-app.web.app/demo/app-datepicker.html

_Originally posted by @claviska in https://github.com/AlaskaAirlines/auro-calendar/issues/8#issuecomment-1012417815_

**Comment by michaelwarren1106** [comment]
I think I had a different component in mind than maybe Cory did. I think that an event calendar and a picker calendar are two wholly different things with wholly different needs. I think adding like full-featured event data slots that would hardly ever get used in a date picker form seems like bloat. I would prefer two components that just happen to share the "it renders a grid of days" feature, a calendar for pickers with minimal "what is going on on this day" features, and an event calendar with less "select a date/range, enable/disable days" features and more "view events on days by day/week/month" type features.

If we wanted to externalize the "render a grid of days" stuff so that it could be shared across a calendar picker and an event calendar, that would make a lot of sense.

I'd also press for some more clarity about what is meant by a "grids are out of scope for x-calendar"? Imo x-calendar IS a grid. And I also disagree that having multiple grids belongs at the datepicker level. If there is a requirement to select (and most likely stylize/highlight a date range that goes between 2 months (ie, Feb 28 - March 15th), having two separate components and having to stylize that range at the datepicker level wouldnt necessarily be trivial. The datepicker level wouldnt necessarily know things like "which day is being hovered" in order to provide selection style changes as the user hovers/tabs through days.

I always check travel sites for calendar inspiration, because datepickers are front and center requirements for them.

Here's Kayak:
![image](https://user-images.githubusercontent.com/8377369/149603771-a7f65bd1-df6f-4470-938f-a9d39de0e592.png)

Expedia:
![image](https://user-images.githubusercontent.com/8377369/149603794-c68b0b28-911a-489a-8faa-cc17bd4ba9bd.png)

Airbnb:
![image](https://user-images.githubusercontent.com/8377369/149603839-7c7233b3-42a0-4c38-afaa-adae8436f9b7.png)


Thats the kind of thing I'm thinking of when I think of a cool `x-calendar` component. In all of the above examples, the hover state for a day changes depending on whether or not you've clicked a date to start a range. And if you have, all the days between the one you clicked and the one you're hovering change style somehow to indicate the range, and the one you are hovering on has the same style as the selected range start.

my ideal API for x-calendar would include an internal range selection feature across multiple month grids, and would just event back out (to the datepicker level) the selected range, so that all the datepicker level needs to do is fill an input with that range value, etc. It could even validate that the range is valid and such.

All in all I think there might need to be more clarity on the kind of component we want to standardize on.


That said, I agree about date formatting needing to be flexible for sure!

As for the other design questions. I would personally steer clear of too much carousel-type UI because those are super hard to make accessible, and opt for simpler UI for choosing the month and year, like selects and lists rather than fancy scrolly containers or sticky heading drawer things. For the "grid of days" view, I would opt for the firefox design. its clean and nice. For the "choose a different month/year" view, I think that both chromium and firefox made it too complicated. Just a select with the years and arrows for months seems like the easiest, cleanest UI to me.

(but check out airbnb's next/previous month animations.......they are sick)

**Comment by claviska** [comment]
> I think that an event calendar and a picker calendar are two wholly different things with wholly different needs.

I'm referring to a primitive `<x-calendar>` that can be used in `<x-date-picker>` and `<x-whatever-other-thing>`. Without a day slot, you'd have to reimplement `<x-calendar>` for each use case. Furthermore, I think @blackfalcon's example requires it to show pricing.

<img width="252" alt="CleanShot 2022-01-16 at 10 49 05@2x" src="https://user-images.githubusercontent.com/55639/149667173-f00ad4f0-92e9-4bd3-9bf8-40c0d10b44ce.png">

> If we wanted to externalize the "render a grid of days" stuff so that it could be shared across a calendar picker and an event calendar, that would make a lot of sense.

This could work too, but it would be in lieu of `<x-calendar>`, e.g. some kind of mixin. If we distill it down that far, we lose the ability to compose a simple HTML element such as `<x-calendar>` and now we're locked into using Lit-specific logic. IMO a reusable custom element is more useful than the logic that powers it.

> my ideal API for x-calendar would include an internal range selection feature across multiple month grids, and would just event back out (to the datepicker level) the selected range, so that all the datepicker level needs to do is fill an input with that range value, etc. It could even validate that the range is valid and such.

This makes the primitive more complicated. [Consider my previous comment:](https://github.com/AlaskaAirlines/auro-calendar/pull/8#issuecomment-1012417815)

> Grids: once you have a single calendar component that supports selections, date ranges, etc. the date picker can be composed of as many as you like. IMO grids are out of scope for `<x-calendar>`. That's not to say they're not important, but they'll convolute the primitive and probably belong at the `<x-date-picker>` level.

If I have `<x-calendar>` that renders a single month, it can support a selected date range. If the range falls before and after the current month, the entire month will show as selected. Thus, if you put two `<x-calendar>` elements next to each other and synced their selected dates to Jan 18 – Feb 22, it would render exactly as you intend:

![image](https://user-images.githubusercontent.com/55639/149667543-f7924107-5140-4655-ab74-e5a0ca1e4d48.png)

It's worth clarifying that `<x-calendar>` _should not_ include the month/year picker. The calendar primitive will simply render a single month and emit events when various actions occur (e.g. the user selects a date).

If we go back to the original discussion, what we all really want is `<x-date-picker>`. IMO it makes little sense to build it without a calendar primitive. By breaking it down this far, we can create a multitude of date pickers that use the same underlying calendar, and all the difficult date logic is confined to a single component.

Once we have a solid calendar primitive, a date picker becomes much easier to build. Date pickers are far more opinionated compared to calendars (month/year selection, "carousels," grids, animations, ranges, etc.) and with a calendar, everyone can create the exact date picker they want without reinventing the wheel. That's why I suggest we build out `<x-calendar>` first.

I'm not opposed to offering a well-designed `<x-date-picker>` as part of the dist. I just don't think we should build a house before pouring the foundation.

**Comment by claviska** [comment]
Addendum:

I want to emphasize that date pickers are extremely opinionated components, and providing a single implementation will result in endless feature requests and customizations that we won't be able to agree on. The scope is just too wide, and people use them in very different ways.

In Shoelace, I probably don't care about grids, day slots, or date ranges. Maybe the scope of _my project_ is to offer a single date picker, very much like the browser provides. Need a date range? Use two date pickers.

That advice won't fly for an airline (pun intended) where a date range picker with grid has been A/B tested to maximize conversions.

We can't build a date picker for _everyone_, but we _can_ build a solid primitive and a basic date picker on top of it that solves 90% of use cases. For the other 10%, here's how you can roll your own with `<x-calendar>` or fork and extend `<x-date-picker>`.

**Comment by michaelwarren1106** [comment]
@claviska i think i see what you’re getting at now, and i generally am on board. the day slot makes sense to me in general, but the part i’m struggling with would be how the day slot and the day number interact? imo `x-calendar` should be in charge of rendering the day numbers. so if you have a day slot, i guess i can’t envision what the day slot logic looks like if you need different slotted content on different days. would each day have a differently named slot?  `<div slot=“jan-20”>` or something like `<div slot=“day”>`?

i’m also not arguing for making the whole picker. the grid primitive is what we’re after. 

could you maybe outline your idea about how range selection might work with two separate x-calendars? in my mind it might be something like: 

calendar 1 & 2 have `type=range`
calendar 1 has a date selected and emits `dateSelected’ 
calendar one has hovers for that month
event handler for dateSelected in the picker somehow notifies calendar two that a range selection has started and sets something on calendar two?

would the calendars needs to know (or self calculate) what order they are in? seems like in order for hovering/ range highlighting to work across separate calendars the calendar order would matter? like one calendar has to be the “from” and the other has to be the “to”

**Comment by claviska** [comment]
> the part i’m struggling with would be how the day slot and the day number interact?

We can dive into those details more, but "day slot" is probably a poor name. It's likely better to use a property that accepts a callback:

```ts
const renderDay = (date: Date) => {
  return html`<span class="my-custom-thing">...</span>`
};
```

We can talk about the use of Lit-specific `html` vs. raw HTML and the associated security risks, but I don't see another way to tackle this cleanly without a function.

> could you maybe outline your idea about how range selection might work with two separate x-calendars?

There wouldn't be a `type="range"` on the primitive. That would be facilitated by the date picker component, which listens for selection/hover events and sets each calendar's `rangeStart` and `rangeEnd` properties as the user interacts. The neat thing about this approach is you can create a full 12-month grid, sync all the calendars using the same range properties, and selection visualization will "just work."

> would the calendars needs to know (or self calculate) what order they are in?

Nope, the date picker will control that. As long as each month of the grid is rendered in order (Jan, Feb, Mar, etc.) it will feel natural to the user.

> seems like in order for hovering/ range highlighting to work across separate calendars the calendar order would matter?

The date will be passed in the hover/select event's payload. One edge case you'd need to consider at the `<x-date-picker>` level is if you're rendering "grayed out" dates from previous/next month, e.g.

![CleanShot 2022-01-16 at 11 59 22@2x](https://user-images.githubusercontent.com/55639/149669870-b1de231b-793a-42f8-a09f-3126aee245be.png)

In that case, if the grayed out dates are selectable that could be confusing to users. But in a grid view, I would probably elect _not_ to show them.

> like one calendar has to be the “from” and the other has to be the “to”

Think of `<x-calendar>` as a function that you control with attributes/properties. Everything must be configurable from that, and the events it emits will have sufficient feedback to facilitate selection and other features a date picker is likely to need.

---

If we're all on board with the calendar primitive concept, the next step is to detail the properties and events it will need. Some initial ideas (everything is TBD):

- `month` - the month to render
- `year` - the year to render
- `startRange|endRange` - if set, the calendar will render a date range between these values (values can be before/after the current month)
- `showAdjacentDays` - when true, the calendar will render "grayed out" days as shown in the image above
- `disabledDays` - a function that receives a date as its only argument. If it returns true, the target date will render "disabled"
- `renderDay` - a function that receives a date as its only argument. It can return the HTML to use for the target day OR an amendment that gets "slotted" into the date.
- etc.

I'd suggest looking at other date pickers for further API inspiration. It will also be helpful to outline what everyone in this thread wants from `<x-date-picker>` so we can make sure the primitive will support it.

**Comment by blackfalcon** [comment]
Just my $0.02 before we move forward. Just FYI... I am 99% on board with everything said in this discussion. The 1% is only requiring additional understanding. 

Regarding the day element slot, since a user will be primarily communicating with `<x-calendar>`, we will need some kind of API that allows a user to map content to a day. For our needs, there is a clear need for this as there is intent to display different kinds of content e.g. price, weather, or a link for example. 

Given the architecture you are proposing @claviska how would you see this working? I am assuming that the date object would be mapped over and output the individual day elements with the date number in the first slot, then a hidden slot that will have the long version of the date, e.g. April 12th, 2022 for a11y. 

The content per slot would be bound to a specific date so my knee-jerk is to consider how to augment that date object to have the additional content and then display that in the optional slot. 

Outside of this `the next step is to detail the properties and events it will need.` yes.

**Comment by claviska** [comment]
I think the term "slot" is causing confusion. I wouldn't want to slot in 30 different things to customize each day. That's why I suggested a property that accepts a callback. The calendar will iterate each day in the month being displayed and render the result of the callback.

Something like this, for example (proper date comparison omitted for clarity):
```ts
const calendar = document.querySelector('x-calendar');
const blocked: Date[] = [...];

calendar.renderDay = (date: Date) => {
  if (blocked.includes(date)) {
    return html`
      <em>Unavailable</em>
    `;
  }
};
```

As this data is likely to come from a backend source, a declarative approach for doing this with `<slot>` will probably make it harder for both the component authors to maintain and end users to consume.

**Comment by blackfalcon** [comment]
> If we're all on board with the calendar primitive concept, the next step is to detail the properties and events it will need. Some initial ideas (everything is TBD) ...

I feel that this thread came to a clear conclusion. Next step would be to update the document in this PR with a specification. https://github.com/AlaskaAirlines/auro-calendar/pull/8/files

You guys want me to take a 1st draft at this, or is there another volunteer who wants to do this?

**Comment by blackfalcon** [comment]
@claviska @michaelwarren1106 we (the Auro team) are going to come together can start to develop the 1st draft of the spec for the custom element. 

If you have anything outside these threads that you want to contribute, please let me know.

**Comment by claviska** [comment]
Who needs a spec? 🙃 https://shoelace-8dzn2q47t-shoelace.vercel.app/components/calendar

The trouble with specs are that you don't know what you need until you know. This calendar is still pretty early, but it does a lot already.

- Renders any month/year
- Date selection (one or more; selected dates don't have to be sequential)
- Localizes months/days (without language packs)
- Optionally show adjacent dates
- Optionally show and customize a calendar border
- Lots of day parts for custom styling
- Event when the month/year changes

Much of the calendar logic was extracted and, for now, [lives here](https://github.com/shoelace-style/shoelace/blob/calendar/src/internal/calendar.ts). It could be valuable to non-Lit calendars and might even merit a separate project with its own tests.

What's left:

- Keyboard navigation for days (needs a roving tab index and support for arrow keys)
- Ability to start the week with Sunday or Monday
- Ability to show week numbers
- Alternate view to select month/year (I kinda like how Firefox does it rather than using a `<select>` for both)
- Min/max range
- Advanced date rendering (e.g. disabling dates, rendering custom content in a date)
- Think more about events we'll need to facilitate a date picker component
- Add more parts for customization

Open questions:

- Months have 4-6 rows. Some calendars have the ability to force a six-week grid to prevent it from growing/shrinking when the month changes. Do we care about that?
- Localizing the selected date. Everything is currently happening in the user's local time zone. That's probably fine, but we need to provide a mechanism to "normalize" the date, probably to UTC. What's the best way to handle this?

**Comment by blackfalcon** [comment]
@claviska this is great and yes, this is what I was looking for. The idea here is to get this 'on paper' so that we know how we can split up the work and move forward. I want to digest this, update that PR so that this is a document we can all refer too and then let's start working on this.

**Comment by michaelwarren1106** [comment]
> Keyboard navigation for days (needs a roving tab index and support for arrow keys)

Westbrook has a roving tab index we could use i bet. i think he was thinking about publishing it under open-wc, but we should dev check with him on it

this looks like a great start! i’m down to pick some features and add to this. 

would we want to externalization it from shoelace and publish standalone or keep it there and just collectively agree to use it and help cory support it?

**Comment by michaelwarren1106** [comment]
i could maybe take the date disabling stuff? what would the approach be? we all take a feature, propose a spec for that feature and agree on it? or build it as a draft pr and get agreement in the comments?

**Comment by claviska** [comment]
> would we want to externalize it from shoelace and publish standalone

At some point, yes. I threw it into a Shoelace branch because it's familiar, a repo already exists, and I don't have to deal with tooling and other things right now. I'm fine with messing with it here and splitting it out and generalizing it once all the core features are implemented. (Alternatively, whoever's interested can take what's there and adapt it under MIT like the rest of the code.)

A generalized version shouldn't live in Shoelace because I'm using opinionated things such as the `LocalizeController`, the `HasSlotController`, a custom `@watch` decorator, etc.

I'll keep tinkering with it on the side. I don't need any help with code just yet, but some feedback on the APIs next steps would be good.

Thinking out loud about some things:

### Should there be a single property that handles date-specific rendering?

We want to support things like date ranges, disabled dates, and custom content. Currently, only the selection logic has been implemented and it looks like this:

```js
const calendar = document.querySelector('my-calendar');

calendar.selectedDates = [
  new Date(today.getFullYear(), today.getMonth(), 12),
  new Date(today.getFullYear(), today.getMonth(), 13),
  new Date(today.getFullYear(), today.getMonth(), 14),
  new Date(today.getFullYear(), today.getMonth(), 15)
];
```

It's an ugly example, but in short it accepts an array of `Date` objects and renders them as selected. Following this pattern, disabled dates would look something like this:

```js
const calendar = document.querySelector('my-calendar');

calendar.disabledDates = [
  new Date(today.getFullYear(), today.getMonth(), 12),
  // ...
];
```

And yet another for rendering custom content:

```js
const calendar = document.querySelector('my-calendar');

calendar.customContent = (date) => {
  // date comparison logic here
  return html` <span class="birthday">Bob's Birthday</span> `;
});
```

An alternative is a single property:

```js
const calendar = document.querySelector('my-calendar');

calendar.onRender = (date) => {
  // date comparison logic here
  return {
    isSelected: false,
    isDisabled: false,
    content: html` <span class="birthday">Bob's Birthday</span> `
  };
});
```

After typing this out, I think I like keeping them as separate properties. Thoughts?

### Local time vs UTC

Right now, everything happens in the user's local time. The month year are dictated by the `month` and `year` attributes.

```html
<sl-calendar month="2" year="2022"></sl-calendar>
```

Do we need to allow for a timezone to be set? What would that look like? @WickyNilliams do you have any insights here?

### Min/max

We need this to prevent the calendar from navigating before or after the min/max options, when set. I'm not sure what this looks like, though. We could accept a `Date` object, but that's a bit cumbersome.

```js
const calendar = document.querySelector('my-calendar');

calendar.minDate = new Date(...);
calendar.maxDate = new Date(...);
```

I'm thinking of allowing `string | Date` like in some of the [date utilities](https://shoelace.style/components/format-date). This lets you pass an ISO string as short as `2022-02-04` or a proper `Date` object, but if you don't use a fully qualified ISO string, you might run into some edge case quirks with timezones.

Any thoughts on this?

**Comment by claviska** [comment]
One more question...what about the month/year selection? Dropdowns are fast-ish but they require at least four clicks to set the month/year. Duet, for example:

<img width="351" alt="CleanShot 2022-02-04 at 11 27 06@2x" src="https://user-images.githubusercontent.com/55639/152565612-a93fab9a-0f52-43ea-9121-87339d981268.png">

This is by far the easiest to implement, but the concern is the system `<select>` is ugly and libraries that implement a custom version will see a visual misalignment and behavior differences.

Chrome's date picker has the following alt view which requires three clicks for month/year selection:

<img width="253" alt="CleanShot 2022-02-04 at 11 24 59@2x" src="https://user-images.githubusercontent.com/55639/152565263-d14c96bc-4ba3-4a93-ab42-9df503755694.png">

It's more efficient click-wise, but I don't find it _easier_. It would require a separate component to do this right, too.

Firefox:

<img width="300" alt="CleanShot 2022-02-04 at 11 29 35@2x" src="https://user-images.githubusercontent.com/55639/152565960-669a43ce-8187-4d65-8c09-210cf398a3c4.png">

It's four clicks to select both month/year and I find it easier to use than Chrome, but it still requires a separate "spinner" component. Maybe that's OK, as a spinner seems much easier and reusable than Chrome's month/year selector.

Safari:

<img width="173" alt="CleanShot 2022-02-04 at 11 31 42@2x" src="https://user-images.githubusercontent.com/55639/152566295-7eed31c4-5a14-4d76-a179-7a73f9e8bf47.png">

WTF, Safari. You can't select a new month/year without clicking through them one-by-one.

One last option is to not provide a month/year picker in the calendar. Instead, we could provide a `<header>` and `<footer>` slot so you can slot in your own controls. For example, in Shoelace I could use `<sl-select>` for month/year and provide a "Go to today" button in the footer that are consistent with the rest of my UI.

```html
<sl-calendar>
  <header slot="header">
    <sl-icon-button name="chevron-left" label="Previous Month">...</sl-icon-button>
    <sl-select label="Month">...</select>
    <sl-select label="Year">...</select>
    <sl-icon-button name="chevron-right" label="Next Month">...</sl-icon-button>
  </header>

  <footer slot="footer">
    <sl-button>Go to Today</sl-button>
  </footer>
</sl-calendar>
```

This gives users full customization of the calendar's UI, so whatever buttons/selects/icons you're using will align with the rest of the app (this is a common pitfall of existing date pickers). I believe it will also eliminate localization needs, since days/months are generated automatically.

The only expense is having to wire things up. In the example above, you'd need to:

- Bind month/year to each `<sl-select>`
- Call `calendar.goToPreviousMonth()` and `calendar.goToNextMonth()` when clicking the icon buttons
- Call `calendar.goToToday()` when clicking on the button in the footer

I'm open to thoughts here.

**Comment by blackfalcon** [comment]
> Westbrook has a roving tab index we could use i bet. i think he was thinking about publishing it under open-wc, but we should dev check with him on it

@michaelwarren1106, that's good stuff... I just wrote something similar in a smaller context. 

https://github.com/AlaskaAirlines/auro-menu/blob/dsande/a11yReview/src/auro-menu.js

**Comment by blackfalcon** [comment]
There is so much to digest in this thread. Next week I really looking to capture all of this in a single document that we can review and iterate on. Right now, there is a lot of data here to try to maintain.

**Comment by michaelwarren1106** [comment]
>Should there be a single property that handles date-specific rendering?

The way we did it previously at Capital One when we wrote our calendar from scratch is using separate props for granularity, so I'd propose attributes/props like

`disable-weekends`
`disable-past-dates`
`disable-future-dates`

then for specific, possibly random, not-calculable dates:
`disabled-dates` or `disabled-days` that would accept an array of dates in some format that would be disabled.

We already have the comparison logic, so we could just add:

```
return {
    isSelected: false,
    isDisabled: isWeekend && options.disableWeekends || isPastDate & options.disablePastDates || ...rest,
    content: html` <span class="birthday">Bob's Birthday</span> `
  };
```

Its a pretty long calculation to decide if a date is disabled or not, but the simplicity of the consuming dev not having to calculate stuff the datepicker is already doing like weekends, past, future, etc I think helps.

On the date selection stuff:
> One last option is to not provide a month/year picker in the calendar

I think this is the most flexible option, because every design system is gonna have its own inputs, etc. They are all gonna be different sizes etc, so I think the slot idea makes the most sense. We'd just need to provide an API for setting the month/year declaratively/programmatically so that events from those elements work properly

On the min/max date stuff:
Do we really need to send in a full date object for that? Isn't just month/year enough for a max/min feature? Since the calendar is defaulting to a month view, we'd only need a month and a year to decide when to NOT render a new month, we wouldnt need the rest of a date obj, so parsing it out only to get at the month year seems like bloat when we could just accept a month and year directly and do direct comparison without parsing a date obj.

**Comment by claviska** [comment]
> BTW i had time this weekend and ported duet picker to lit, split out the calendar part, improved a load of existing features, and added some new ones

![giphy](https://user-images.githubusercontent.com/55639/152816911-62983c0e-b1e7-4a6c-be13-a9a79ec25d9a.gif)

> i would personally like it to not be tied to a company as is here.

I second this. And I don't think @blackfalcon intended it to be tied to Alaska, it was just a convenient place to start the conversation. Same reason I threw my prototype in the Shoelace repo.

Folks, if he's willing, I suggest letting @WickyNilliams take the lead on this since his date picker is way more established and tested than anything we're going to whip up on our own.

@WickyNilliams how do you feel about this? Do you generally agree with the direction we're going thus far? What sort of support do you need from us to get the project closer to completion?

**Comment by blackfalcon** [comment]
WOW! This is a pretty amazing turn of events TBH! And yes, @WickyNilliams there was no intent of binding this to Alaska, this was just for convenience. 

> @WickyNilliams how do you feel about this? Do you generally agree with the direction we're going thus far? What sort of support do you need from us to get the project closer to completion?

I second this... there is no reason for us to stop momentum on this at all! And yes, how can we all help?

**Comment by WickyNilliams** [comment]
Excuse the brief message earlier, I was eating my lunch at the time :)

> There was no intent of binding this to Alaska, this was just for convenience

Oh OK! My misunderstanding. I only mentioned it because of course duet was tied to a company, and I was only a contractor there, so it's under their control now. That's why I wanted to make sure it was community based. 

I have no finally gone through this thread in detail, and I think I'm largely on board with what has been discussed. I think we can have building blocks to support the vast majority of use cases from simple date picker up to multi month views with range select etc. 

At the moment I want to move pretty fast (and possibly break things as I go), and I think the collaboration/communication overhead would slow things down for now. When the code has stabilised a little, we can work out what to do next and how to continue? 

I hope that's OK! I've very keen to make this a community effort in the end.

**Comment by claviska** [comment]
Yes! Dumb primitives make for smart compositions. This looks very promising!

**Comment by michaelwarren1106** [comment]
sounds good to me! Let me know where we are gonna put some code so we can start tackling features like we've discussed above

**Comment by WickyNilliams** [comment]
Any chance you could put together a distilled list of requirements/features, so I don't need to make guesses from the thread? That way I can keep an eye on the goal

**Comment by michaelwarren1106** [comment]
Ok cool, should I make a new issue somewhere with that list? or just keep it here in a comment?

Things I know we've discussed are:

- date range support, configurable styling
- a method to render extra stuff on a day box
- multiple date format support for i18n
- show/hide dates adjacent to current month
- min/max dates
- lots of ways to disable dates:
  - disable weekends
  - disable past dates
  - disable future dates
  - disable arbitrary dates
- highlight dates
- highlight today
- local time vs specified timezone
- day name config (Sun vs S vs Sunday)
  - i18n for day names
- month name config (Feb vs February)
  - i18n for month names
- optionally show week numbers
- lots of events all over the place when things happen

what else am I missing?

**Comment by blackfalcon** [comment]
Per this discussion, I have updated the contest of this PR https://github.com/AlaskaAirlines/auro-calendar/pull/8/files. All additional discussions should happen within this PR to refine the spec.

**Comment by jason-capsule42** [comment]
Current version of Calendar matches latest [Figma](https://www.figma.com/file/mZzZNE0cEPnphZozbaZfDy/Calendar?node-id=1325%3A6204).

Further changes will be handled as separate tickets
